---
- hosts: all
  become: yes
  vars:
    NODEJS_VERSION: "14"
    ansible_distribution_release: "focal"
  tasks:
    - name: Install the gpg key for nodejs LTS
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present
    - name: Install the nodejs LTS repos
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes
    - name: Install the nodejs
      apt:
        name: nodejs
        state: latest
    - name: Install the latest NPM
      npm:
        name: npm
        global: yes
        state: latest
    - name: Install app dependencies defined in package.json.
      npm: path=/vagrant/data/client
